---
roles:
  - src: https://github.com/chriswayg/ansible-msmtp-mailer/archive/refs/tags/v0.6.1.tar.gz
    name: chriswayg.msmtp-mailer
    type: git

collections:
  - name: https://github.com/ansible-collections/community.docker
    type: git
  - name: https://github.com/ansible-collections/community.general
    type: git
  - name: https://github.com/ansible-collections/community.crypto
    type: git
  - name: https://github.com/ansible-collections/ansible.posix
    type: git
