---
- name: Install UFW
  ansible.builtin.package:
    name: ufw
    state: present

- name: Enable UFW logging
  community.general.ufw:
    # yamllint disable-line
    logging: on

- name: Check if the 'UFW configured' marker file exists
  ansible.builtin.stat:
    path: "{{ docker_dir }}/.ufw_configured"
  register: ufw_configured

- name: Configure UFW
  block:
    - name: Reset all rules
      when: not ufw_configured.stat.exists
      community.general.ufw:
        state: reset

    - name: Create the marker file
      when: not ufw_configured.stat.exists
      ansible.builtin.file:
        dest: "{{ docker_dir }}/.ufw_configured"
        state: touch

    - name: Allow the defined ports
      community.general.ufw:
        rule: allow
        proto: "{{ item.proto }}"
        port: "{{ item.port }}"
      with_items:
        - "{{ ufw_ports }}"

    - name: Deny everything else and enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
  rescue:
    - name: Grant SSH access to prevent lockout
      community.general.ufw:
        rule: allow
        port: "{{ ssh_port }}"
        proto: "tcp"

    - name: Deny everything else and enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
